# Generated by Django 2.1.5 on 2019-01-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('user_last_name', models.CharField(max_length=15)),
                ('dob', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
